### ISSUE TITLE
Expanding certain tree items collapses entire tree

### ISSUE THREAD

**Issue by ryon** [SlateFoundation/slate-admin#69]
Perhaps a duplicate ID issue?

**Steps**

1. Load /SlateAdmin/?apiHost=demo.v2.slate.is/#settings/groups
2. Expand Alumni
3. Attempt to expand Class of 2014

**Expected**
Class of 2014 expands

**Actual**
Alumni collapses, along with any other open nodes

**Comment by aharley40** [comment]
@ryon I couldn't reproduce this. Are there any more steps?

**Comment by themightychris** [comment]
@ryon try this out on an updated build today, it might have been accidentally fixed in another issue

**Comment by ryon** [comment]
@themightychris Still happens for me. `development` branch, `demo.v2.slate.is` as the `apiHost`.

**Comment by themightychris** [comment]
It was an issue with a leaf state corruption in the backend table
